db.Statement.ReflectValue不是指针型的时候panic
go-gorm/gorm pull request #5194
Opened 2022-03-27 12:58 UTC by johnnylei

fix:  db.Statement.ReflectValue不是指针型的时候BeforeCreate, AfterCreate, BeforeUpdate, AfterUpdate会panic

比如下面这种

```
type OperationStep {
    ID int64
    State uint
}

func (o *OperationStep) AfterUpdate(tx *gorm.DB) error {
	return nil
}

db.Model(OperationStep{}).Where("id=?", operationStep.ID).Update("state", types.OperationStateSuccess).Error
```

2022-03-27 14:22 UTC, jinzhu commented
Hi @johnnylei 

Can you add some tests?

2022-03-28 06:13 UTC, a631807682 requested changes
We should handle the following situations 
1. addressable struct
2. element of a slice
3. element of an addressable array

Seems we should fix it in `callMethod`

2022-04-03 04:20 UTC, johnnylei commented
> 

案例已经提供, 上面的测试panic， 就已经说明这个问题了

2022-04-03 04:22 UTC, johnnylei commented
test code
```
testPanic := Product2{Name: "testPanic", Price: 100}
	DB.Create(&testPanic)
	DB.Model(Product2{}).Where("name", "testPanic").Update("name", "testPanic1")
```
response
```
--- FAIL: TestUseDBInHooks (0.02s)
panic: reflect.Value.Addr of unaddressable value [recovered]
	panic: reflect.Value.Addr of unaddressable value

goroutine 8547 [running]:
testing.tRunner.func1.2({0xe22c00, 0xffd390})
	/opt/hostedtoolcache/go/1.17.8/x64/src/testing/testing.go:[120](https://github.com/go-gorm/gorm/runs/5803672705?check_suite_focus=true#step:6:120)9 +0x36c
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.17.8/x64/src/testing/testing.go:[121](https://github.com/go-gorm/gorm/runs/5803672705?check_suite_focus=true#step:6:121)2 +0x3b6
panic({0xe22c00, 0xffd390})
	/opt/hostedtoolcache/go/1.17.8/x64/src/runtime/panic.go:1047 +0x266
reflect.Value.Addr({0xe9ad20, 0xc0000cc5a0, 0x1919000000485e25})
	/opt/hostedtoolcache/go/1.17.8/x64/src/reflect/value.go:273 +0x8e
gorm.io/gorm/callbacks.callMethod(0xc0006d0180, 0xc000693900)
	/home/runner/work/gorm/gorm/callbacks/callmethod.go:20 +0x1cd
gorm.io/gorm/callbacks.BeforeUpdate(0xc0006d0180)
	/home/runner/work/gorm/gorm/callbacks/update.go:39 +0x1aa
gorm.io/gorm.(*processor).Execute(0xc000202690, 0xc0006d0180)
	/home/runner/work/gorm/gorm/callbacks.go:130 +0xbe9
gorm.io/gorm.(*DB).Update(0xc000201110, {0xecadc9, 0x4}, {0xe22c00, 0xffc690})
	/home/runner/work/gorm/gorm/finisher_api.go:334 +0x198
gorm.io/gorm/tests_test.TestUseDBInHooks(0xc0004f6000)
	/home/runner/work/gorm/gorm/tests/hooks_test.go:259 +0x6ce
testing.tRunner(0xc0004f6000, 0xf01f70)
	/opt/hostedtoolcache/go/1.17.8/x64/src/testing/testing.go:[125](https://github.com/go-gorm/gorm/runs/5803672705?check_suite_focus=true#step:6:125)9 +0x230
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.17.8/x64/src/testing/testing.go:[130](https://github.com/go-gorm/gorm/runs/5803672705?check_suite_focus=true#step:6:130)6 +0x727
FAIL	gorm.io/gorm/tests	3.017s
FAIL
Error: Process completed with exit code 1.
```

2022-05-28 15:10 UTC, closed without merging

2022-05-28 15:11 UTC, jinzhu commented
Closing this PR as CI failed.